[codecrate]
output = "context_phrasplit.md"
keep_docstrings = true
dedupe = true
respect_gitignore = true
exclude = ["examples", "*/.venv/*"]
include = ["**/*.py", "**/*.toml", "**/*.rst"]
split_max_chars = 25000000
layout = "full"

